### ISSUE TITLE
EPIC: mejoras al autocompletado

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-lsp-ide#105]
- [ ] Autocomplete: darle formato (https://github.com/uqbar-project/wollok-lsp-ide/issues/69)
- [ ] Cuando estás al final del archivo o en el medio de dos elementos (Class / Object) piensa que estás dentro del elemento anterior
      Es un problema del parser, reportado en wollok-ts https://github.com/uqbar-project/wollok-ts/issues/173
- [ ] Cuando escribís no te filtra el autocompletado (el problema estaba en que cuando había un error defaulteaba el nodo al primer 
      ancestro que no tuviera problems, entonces si escribís "m" de method eso da error al parsear y se rompe, y subía a nivel Package
      donde el "method" no es un autocompletado posible
- [ ] Revisar el autocompletado por elementos
      - [ ] Clase
      - [ ] Singleton
      - [ ] Objeto anónimo
      - [ ] Mixin
      - [ ] Describe
      - [ ] Test
      - [ ] Package
      - [ ] Import
- [ ] Agregar testeo unitario de la funcionalidad
- [ ] Revisar el testeo de integración de Wollok LSP-IDE
- [ ] Autocomplete con prioridad: https://github.com/uqbar-project/wollok-lsp-ide/issues/53 , hay que ver si podemos ordenar por criterio
- [ ] Que la sugerencia de mensajes no considere el punto si el mismo tiene chirimbolos: https://github.com/uqbar-project/wollok-lsp-ide/issues/85
- [ ] Evitar el autocomplete de mensajes en el import: https://github.com/uqbar-project/wollok-lsp-ide/issues/74
- [ ] El original: https://github.com/uqbar-project/wollok-lsp-ide/issues/36, no mostrar los snippets en todas las situaciones

**Comment by fdodino** [comment]
Lo cierro porque ya puse las tasks en la épica
