### ISSUE TITLE
[EPIC] Debugger

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/wollok-lsp-ide#182]
- [ ] Output (para resultados de tests y excepciones)
- [ ] Logger
- [ ] Nodos sin sourcemap (e.g. `energia += 10`)
- [ ] Mejorar UX launch, que se pueda launchear como el REPL (desde un boton de play)
- [ ] Stop on unhandled exceptions / all exceptions
- [ ] Evaluar mientras debuggeo
     - [ ] Debug Console
     - [ ] Watch List
- [ ] Breakpoints
    - [ ] Conditional breakpoints
    - [ ] Breakpoint locations (dar mas granularidad que solo poner un breakpoint en la linea)
